### PR TITLE
Fix package name for Generated Controllers

### LINKED ISSUE #163: Controller package generation through the CLI creates a file in a package `controller` instead of `controllers`, in the `controllers` folder
**To Reproduce**

1. Run `go run github.com/go-fuego/fuego/cmd/fuego@latest controller books`
2. Try to follow documentation steps.
3. Get an error because package controllers does not exist.

**Expected behavior**
- Package controllers should exist.
- We should be able to call `controllers.BooksRessources{}.Routes(s)` without having to change the package name inside of the generated file.

**Screenshots**
N/A

**Framework version (please check if it happens with the last
Fuego version before posting):** `v0.14.0`

**Go version (please check if it happens with the last Go version before posting):**  `go1.22.6 darwin/amd64`

**Additional context**
The docs are partially correct because of this; we need to make a decision whether to keep controllers vs controller and ensure the docs follow this naming convention. If we decide to keep `controller` as the package name, I'd suggest renaming the folder and we still need to update the example in the docs accordingly.

### PR DESCRIPTION
**Pull request by asahasrabuddhe**
Fixes #163

### CODE REVIEW

**Comment by asahasrabuddhe** [comment]
@EwenQuim do you mind reviewing this once you have a moment?

**Review by EwenQuim — CHANGES_REQUESTED** [review]

**Comment by EwenQuim** [comment]
Sorry my comment was left pending

File: cmd/fuego/commands/controller.go [hunk 1]
```diff
@@ -53,7 +53,8 @@ func createController(controllerName string) (string, error) {
 	t := language.English
 	titler := cases.Title(t)
 
-	newContent := strings.ReplaceAll(string(templateContent), "newController", controllerName)
+	newContent := strings.ReplaceAll(string(templateContent), "package controller", "package controllers")
```
[the remark this answers is not in the document]
Comment (asahasrabuddhe) [reply cmd/fuego/commands/controller.go:56]: Sure

File: cmd/fuego/templates/controller/controller.go [hunk 2]
```diff
@@ -1,4 +1,4 @@
-package controller
+package controllers
```
Comment (EwenQuim) [inline cmd/fuego/templates/controller/controller.go:1]: I'm really sorry but could you change the folder name instead of the package name ?

Singular is preffered in Go

**Review by EwenQuim — CHANGES_REQUESTED** [review]

File: cmd/fuego/templates/controller/controller.go (hunk 2 above)
Comment (asahasrabuddhe) [reply cmd/fuego/templates/controller/controller.go:1]: Do you mean the name of the generated folder?

Comment (asahasrabuddhe) [reply cmd/fuego/templates/controller/controller.go:1]: I am happy to do this, but we must consider that this will be a breaking change for anyone who has an existing `fuego` project. The updated CLI would write new controllers in the `controller` folder, while the existing folder would be called `controllers`.

Comment (EwenQuim) [reply cmd/fuego/templates/controller/controller.go:1]: Yes ! People will rename their folder, it's not costly

The other way around was also a breaking change

Comment (asahasrabuddhe) [reply cmd/fuego/templates/controller/controller.go]: Done!

**Review by EwenQuim — APPROVED** [review]
