### PR TITLE
fix: init groups server with new server.RouteOptions when Grouping

### LINKED ISSUE #478: Middleware not consistently applied in nested route groups
**To Reproduce**

1. Create a parent route group with middleware (e.g., TestMiddlewareOne)
2. Create a child route group from the parent with additional middleware (e.g., TestMiddlewareTwo)
3. Define a route on the child group (works correctly with both middlewares)
4. Define a route on the parent group (works correctly with parent middleware only)
5. Define another route on the child group
6. The second route on the child group only applies the parent middleware, not the child middleware

Commit for repro (uses the petstore example): [test: Reproduce bug (child group's middleware gets dropped)](https://github.com/go-fuego/fuego/commit/eec990592d869e424b3456de9e945d9f4a71073c)

Example code:
```go
// Create parent group with middleware 1
petsGroupOne := fuego.Group(s, "/pets", option.Middleware(TestMiddlewareOne))

// Create child group with middleware 2
petsGroupTwo := fuego.Group(petsGroupOne, "", option.Middleware(TestMiddlewareTwo))

// Works correctly - applies middleware 1
fuego.Get(petsGroupOne, "/", rs.filterPets)

// Works correctly - applies middleware 1 and 2
fuego.Get(petsGroupTwo, "/all", rs.getAllPets)

// Works correctly - applies only middleware 1
fuego.Post(petsGroupOne, "/generic-response", rs.genericRequestAndResponse)

// BUG: Only applies middleware 1, should apply both 1 and 2
fuego.Get(petsGroupTwo, "/by-age", rs.getAllPetsByAge)
```

**Expected behavior**
All routes defined on the child group should consistently apply both the parent and child middlewares, regardless of the route definition order.

**Framework version**
v0.18.6

**Go version**
v1.23.8

**Additional context**
The bug is caused by inconsistent behavior with slice sharing in Go. When creating a child group, the routeOptions slice isn't properly initialized, causing it to share its underlying array with the parent. Subsequent append operations can cause reallocations that lead to inconsistency.

I will fork the repo and create a PR, appreciate if you could take a look!

### PR DESCRIPTION
**Pull request by dylanhitt**
Closes #478 

There may be a more elegant way of doing this. But I'm not sure how.

### CODE REVIEW

**Comment by dylanhitt** [comment]
@EwenQuim is this fine to merge?

File: net_http_mux.go [hunk 1]
```diff
@@ -23,23 +23,23 @@ import (
...
 func Group(s *Server, path string, routeOptions ...func(*BaseRoute)) *Server {
-	if path == "/" {
+	switch {
+	case path == "/":
 		path = ""
-	} else if path != "" && path[len(path)-1] == '/' {
-		slog.Warn("Group path should not end with a slash.", "path", path+"/", "new", path)
+	case strings.HasSuffix(path, "/"):
+		slog.Warn("Group path should not end with a slash.", "path", path, "new", strings.TrimSuffix(path, "/"))
 	}
```
Comment (ccoVeille) [inline net_http_mux.go]: Maybe you could use CutSuffix that returns a bool flag

This way it would look like this (pseudo code)

```suggestion
	case cleaned, found := strings.CutSuffix(path, "/"); found:
		slog.Warn("Group path should not end with a slash.", "path", path, "new", cleaned)
	}
```

Comment (dylanhitt) [reply net_http_mux.go]: How does that look now? You can't instantiate inside case statement AFAIK.
